config/routes.rb
Rails.application.routes.draw do
  root 'things#index'
  resources :things
  devise_for :users

  get "things/change_session_date/:date" => "things#change_session_date"

end

app/models/thing.rb
class Thing < ActiveRecord::Base
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)
    @thing.user_id = current_user.id

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_session_date
    session[:date] = '2017-01-01'
    @date = params[:date] 
    puts @date
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:title, :icon, :body, :time, :place, :user_id, :day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Scheduler</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css"> -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	<meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<header>
		<div>
			<nav class="menu-drop-down">
				<ul>
					<li></li>
					<li>logout</li>
					<li>oo</li>
					<li>oooo</li>
					<li>ooo</li>
				</ul>
			</nav>
		</div>
		<div class="header-bar">
		</div>
	</header>


	<%= yield %>


	<div id="page-adj"></div>

	<footer>
			<nav>
				<ul>
					<% if current_user.blank? == false %>
						<%= link_to new_thing_path do %><li class="footer-button"><%= image_tag("pencil-with-rubber.png") %></li><% end %>
						<%= link_to things_path do %><li class="footer-button"><%= image_tag("calendar-icon.png") %></li><% end %>
						<span><li class="footer-button"><%= image_tag("setting-tool.png") %></li></span>
					<% else %>
						<%= link_to "Create User", new_user_registration_path %>
					<% end %>
				</ul>
			</nav>
	</footer>




<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
	<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script> -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script> -->
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
	<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
	<script type="text/javascript">
		function getId(ele){
			var attr = ele.getAttribute("id");
			$(".date-button").removeClass("date-selected");
			if (attr != "") {
				$(ele).parent().addClass("date-selected");
			}
			
			$.ajax({
				url: "things/change_session_date/:date",
				type: "GET",
				data: {
					date : attr
				},
				dataType: "html",
				success: function(data) {
					console.log(attr);
				},
				error: function(data) {
					alert('error');
				}
			});
		}

	</script>
</body>
</html>

app/views/things/_calendar.html.erb
<div class="calendar-position">
  <h2 class="calendar-title calendar-table">
    <span id="previous-month" class="month-button"><%= image_tag('back-arrow-circular-symbol.png') %></span>
    <span id="year-js"></span>年 <span id="month-js"></span>月
    <span id="next-month" class="month-button"><%= image_tag('right-arrow-circular-button.png') %></span>
  </h2>
  <table class="calendar-table">
    <thead>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody id="calendar-body-js"></tbody>
  </table>
</div>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_field :day %>
    <%= f.label :time %><br>
    <%= f.time_field :time %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/change_session_date.html.erb
<%= @date %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'calendar' %>

<h2>Listing Things</h2>

<table id="calendar">
  <thead>
  </thead>
  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= link_to thing.title, thing_path(thing) %></td>
        <td><%= thing.day %> <%= thing.time %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

<% form_for @thing do |thing| %>
	<div class="form-group">
		<label for="InputEmail">メール・アドレス</label>
		<input type="email" class="form-control" id="InputEmail" placeholder="メール・アドレスを入力して下さい。">
	</div>
<% end %>

<%= link_to "Back", things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <strong>date:</strong>
  <%= @thing.day %>
</h1>

<p>
  <strong>time:</strong>
  <%= @thing.time %>
</p>
<p>
  <strong>title:</strong>
  <%= @thing.title %>
</p>
<p>
  <strong>icon:</strong>
  <%= @thing.icon %>
</p>
<p>
  <strong>Body:</strong>
  <%= @thing.body %>
</p>

<p>
  <strong>place:</strong>
  <%= @thing.place %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %>